# -*- coding: utf-8 -*-
"""bharath.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRxtpEsLPtZpzCeA2nw3krT8zMybWWPj
"""

def greet(name):
  print("hello",name)
  greet("alice")
  greet("bob")

def add_numbers(a,b):
  return a+b
result=add_numbers(5,7)
print("sum is:",result)

fruits=["apple","banana","cherry"]
print("Fruits:",fruits)
print("First fruit:",fruits[0])
fruits.append("mango")
fruits.remove("banana")
print("updated fruits:",fruits)

def print_fruits(fruit_list):
  for fruit in fruit_list:
    print("fruit:",fruit)
    fruits=["apple","banana","cherry"]
    print_fruits(fruits)

marks=int(input("Enter marks: "))
if marks>=90:
  print("Grade A")
elif marks>=60:
  print("Grade B")
else:
  print("Grade c")

text="Python is Fun"
 print(text.upper())
 print(text[6])

def torque(force,radius):
    return force*radius
    print("Torque:",torque(50,0.3),"n-m")

machine={"name":"lathe","power":5.5,"unit":"kw"}
  print("machine:",machine["name"])
  print("power:",machine["power"],machine["unit"])

tools={"wrench","hammer","screwdriver","hammer"}
print("unique tools:",tools)

def slab_volume(length,width,thickness):
  return length*width*thickness
  print("volume:",slab_volume(5,4,0.15),"m**3")

project={"name":"bridge","length":150,"status":"ongoing"}
print("project:",project["name"])
print("length:",project["length"],"meters")























